### ISSUE TITLE
Socket open error

### ISSUE THREAD

**Issue by wiseguysby** [ssimicro/lib_mysqludf_amqp#10]
I've completed installation, but when I tried running function show error
 (HY000): Can't initialize function 'lib_mysqludf_amqp_sendstring'; lib_mysqludf_amqp_send: socket open error

I used mysql 8.0.16

**Comment by wiseguysby** [comment]
added question, this is MQ connection problem right?

**Comment by tcort** [comment]
> added question, this is MQ connection problem right?

Yes

**Comment by wiseguysby** [comment]
could you guide me, what's problem? bcos I've tested with rabbitmq-c like at https://github.com/alanxz/rabbitmq-c#running-the-examples running well also SELECT lib_mysqludf_amqp_info(); no problem. but when running SELECT lib_mysqludf_amqp_sendstring(...) got error message

**Comment by ikonopistsev** [comment]
Looks like a problem with [amqp_socket_open](https://github.com/ssimicro/lib_mysqludf_amqp/blob/e51490e870fdd3c1b51068ac92ede0cb2105db41/send.c#L66)

lib_mysqludf_amqp_send does not return error code, i think you problem with resolving of host name ([see this](https://rabbitmq-c.docsforge.com/master/api/amqp_open_socket_inner/)).

Try use with ip address.

Also it may be a firewall on rabbitmq pc side.

**Comment by wiseguysby** [comment]
I've trying with ip address, still got problem. fyi I've nodejs apps connect to rabbitmq, its working well. lib_mysqludf_amqp and my nodejs apps and rabbitmq are same machine. I dont know why lib_mysqludf_amqp is not working....

SELECT lib_mysqludf_amqp_sendstring('amqp://guest:guest@localhost:5672', 'udf', 'test', 'Hello, World!');
![Capture](https://user-images.githubusercontent.com/33086336/102612085-b12c4100-4162-11eb-90af-5e1dbcf7dd0c.PNG)

**Comment by ikonopistsev** [comment]
I have nothing to say :) everything looks fine. 

In my work, we tred to use lib_mysqludf_amqp, buy it has bad perfromance. 
1. Becouse It make a new socket connection per trigger.
2. It doesn't support amqp transactions.
3. And this library looks abandoned.

I've impement my own udf, it's analog of this but using stomp protocol.

But i try to check you example with lib_mysqludf_amqp.

**Comment by ikonopistsev** [comment]
<pre>mysql&gt; CREATE FUNCTION lib_mysqludf_amqp_info RETURNS STRING SONAME &apos;lib_mysqludf_amqp.so&apos;;
Query OK, 0 rows affected (0.03 sec)

mysql&gt; CREATE FUNCTION lib_mysqludf_amqp_sendjson RETURNS STRING SONAME &apos;lib_mysqludf_amqp.so&apos;;
Query OK, 0 rows affected (0.01 sec)

mysql&gt; CREATE FUNCTION lib_mysqludf_amqp_sendstring RETURNS STRING SONAME &apos;lib_mysqludf_amqp.so&apos;;
Query OK, 0 rows affected (0.01 sec)

mysql&gt; select lib_mysqludf_amqp_info();
+----------------------------------------------------+
| lib_mysqludf_amqp_info()                           |
+----------------------------------------------------+
| 0x6C69625F6D7973716C7564665F616D717020322E302E30   |
+----------------------------------------------------+
1 row in set (0.00 sec)

mysql&gt; select lib_mysqludf_amqp_sendstring(&apos;amqp://stompdemo:123@127.0.0.1:5672/stompdemo&apos;, &apos;&apos;, &apos;a1&apos;, &apos;Hello, World!&apos;);
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| lib_mysqludf_amqp_sendstring(&apos;amqp://stompdemo:123@127.0.0.1:5672/stompdemo&apos;, &apos;&apos;, &apos;a1&apos;, &apos;Hello, World!&apos;)                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 0x33303037316236382D353362652D343731392D386138632D393066633965343638653936                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.02 sec)
</pre>


I use linux Gentoo, rabbitmq-server-3.8.7, dev-lang/erlang-23.0.4.
rabbitmq 
vhost - stompdemo
login - stompdemo
passcode - 123
exchange - ''
routing_key - a1

RESULT:
```
Exchange | (AMQP default)
-- | --
a1
○
app_id:lib_mysqludf_amqptimestamp:1608296617message_id:30071b68-53be-4719-8a8c-90fc9e468e96delivery_mode:2headers:User-Agent:lib_mysqludf_amqp/2.0.0content_type:text/plain | lib_mysqludf_amqp | 1608296617 | 30071b68-53be-4719-8a8c-90fc9e468e96 | 2 | User-Agent:lib_mysqludf_amqp/2.0.0 | lib_mysqludf_amqp/2.0.0 | text/plain
lib_mysqludf_amqp
1608296617
30071b68-53be-4719-8a8c-90fc9e468e96
2
User-Agent:lib_mysqludf_amqp/2.0.0 | lib_mysqludf_amqp/2.0.0
lib_mysqludf_amqp/2.0.0
text/plain
Hello, World!
```

**Comment by wiseguysby** [comment]
you are lucky :+1: 
Im using centos 7 erlang 23.1 rabbitmq 3.8.8. for this moment im using other strategy without 
lib_mysqludf_amqp, maybe next time. I dont have experience in c language, so need more time to create library by my self.
thanks for your support

**Comment by ikonopistsev** [comment]
If stomp protocol is normal for you, you may try capstomp in my github profile. But we use debain, it not tested on centos.
