### ISSUE TITLE
Extra bytes in messages

### ISSUE THREAD

**Issue by upsala** [ssimicro/lib_mysqludf_amqp#3]
Sometimes, I get extra bytes at the end of an message. amqp_cstring_bytes expects an cstring, mysql-strings are strings with a seperate string-length argument.

**Comment by tcort** [comment]
I'll look into this. Can you provide any more details? Does the issue always happen with certain strings or is it intermittent? What are the values of the extra bytes? etc.

**Comment by upsala** [comment]
When I did this, I got random bytes at the end of each string:
```
create table test(id int);
insert into test(id) values(1),(2),(3);
select lib_mysqludf_amqp_sendstring('localhost', 5672, 'guest', 'guest', 'udf', 'test', concat(id)) from test;
```

The mysql-udf-docu says: "Do not assume that the string is null-terminated." (https://dev.mysql.com/doc/refman/5.7/en/udf-arguments.html) 

I t seems, that the amqp-Library has no function for this, so I tested it with this function:
```
amqp_bytes_t amqp_string(char *str, int length) 
{
  amqp_bytes_t result;
  result.bytes = str;
  result.len = length;
  
  return result;
}
```

**Comment by tcort** [comment]
Thanks for the comment. It got me pointed in the right direction. I ended up just declaring the data like this:

```
    amqp_bytes_t routing_key = {
        .bytes = args->args[2],
        .len = args->lengths[2],
    };
```

`amqp_bytes_t` doesn't have any magic, it's just a pointer to bytes with a length. See [amqp_cstring_bytes](https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_mem.c#L180-L186), so it works nicely with mysql which gives us buffers (`args->args[i]`) and lengths (`args->lengths[i]`).

This change will be in the next release. Just one more issue to go. Thanks again for all of the helpful reports.
