### ISSUE TITLE
Error on make install

### ISSUE THREAD

**Issue by dakorpar** [ssimicro/lib_mysqludf_amqp#7]
Hi, I'm trying to configure this inside docker container, on centOS, I managed to compile it successfully but on make install I get this error. Any info?
mariadb is installed

```
# make install
  CCLD     lib_mysqludf_amqp.la
/usr/bin/ld: cannot find -lmariadb
collect2: error: ld returned 1 exit status
make: *** [lib_mysqludf_amqp.la] Error 1
```
Here are installed MariaDB packages:

```
Installed Packages
MariaDB-client.x86_64                                            10.2.7-1.el7.centos                            @mariadb
MariaDB-common.x86_64                                            10.2.7-1.el7.centos                            @mariadb
MariaDB-compat.x86_64                                            10.2.7-1.el7.centos                            @mariadb
MariaDB-devel.x86_64                                             10.2.7-1.el7.centos                            @mariadb
MariaDB-server.x86_64                                            10.2.7-1.el7.centos                            @mariadb

```

**Comment by tcort** [comment]
I've never used MariaDB nor docker, and I haven't touched CentOS in almost 10 years, so this is mostly a guess until I or someone else investigates further....

It seems that it can't find the shared library for MariaDB. From your report, it seems to be installed, so likely the LDFLAGS required for the linker to find it are missing. The LDFLAGS come from `mysql_config`. From my internet searches, it isn't clear if mariadb installs `mysql_config` or `mariadb_config`. The macros in `lib_mysqludf_amqp`'s build process don't consider mariadb, so if there is no `mysql_config` on your system, it isn't getting the linker flags.

So you might want to try the following....

* see what is installed...
  * do you have `mysql_config`? run `which mysql_config` to find out.
  * do you have `mariadb_config`? run `which mariadb_config` to find out.
* if you only have `mariadb_config`, try this:
  * `./configure --with-mysql=/put/in/full/path/to/mariadb_config`
* if that doesn't work, you can try manually passing the CFLAGS, LDFLAGS, CXXFLAGS, CPPFLAGS, etc to `./configure` based on the output of `mariadb_config`.

**Comment by dakorpar** [comment]
`ln -s /usr/lib64/libmariadbclient.a /usr/lib64/libmariadb.a`
solcved this issue, now I have everything compiled but when running make installdb I get:
```
ERROR 1126 (HY000) at line 3: Can't open shared library 'lib_mysqludf_amqp.so' (errno: 11, undefined symbol: arc4random)
make: *** [installdb] Error 1
```
but I have libbsd installed

**Comment by dakorpar** [comment]
libbsd-devel was missing. Now it's installed successfully
